import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="information literacy information retrieval keyword search intent search expression Boolean operation AND OR NOT exact search site filetype intitle inurl advanced search result filter information source primary source secondary source official documentation paper report news blog forum credibility timeliness authority bias fact-check cross-validation citation copyright academic integrity Google Scholar CNKI Wanfang arXiv IEEE ACM PubMed paper title abstract introduction method experiment conclusion reference reference management Zotero material card tag system knowledge base research question survey report review tech selection report information quality digital literacy media literacy source evaluation data literacy citation style APA MLA Chicago research method literature review systematic review scoping review meta-analysis research question framework PICO SPIDER search strategy database search controlled vocabulary MeSH terms snowballing citation tracking reference harvesting grey literature preprint peer review impact factor h-index altmetrics open access predatory journal research data management data repository data citation research information management reference manager citation network academic profile ORCID Scopus ID researcher identity research workflow";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"in-tag-"+String(i+1).padStart(3,"0"),name:n,category:"InfoLit",description:"InfoLit标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"in-course-01",order:1,slug:"IL入门",title:"信息素养入门与研究能力路线",description:"信息素养定义、研究能力、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"in-course-02",order:2,slug:"SearchEngine",title:"搜索引擎、关键词与检索表达式",description:"搜索原理、关键词设计、布尔运算。",estimatedHours:8,diff:"easy"},
  {id:"in-course-03",order:3,slug:"AdvancedSearch",title:"高级搜索语法与结果筛选",description:"site/filetype/intitle、高级搜索。",estimatedHours:8,diff:"easy"},
  {id:"in-course-04",order:4,slug:"SourceEval",title:"信息源类型、可信度与偏差识别",description:"信息来源分类、可信度判断、偏见识别。",estimatedHours:10,diff:"medium"},
  {id:"in-course-05",order:5,slug:"FactCheck",title:"事实核查、交叉验证与引用意识",description:"核查方法、验证流程、引用习惯。",estimatedHours:8,diff:"medium"},
  {id:"in-course-06",order:6,slug:"AcademicSearch",title:"学术搜索、论文检索与文献数据库",description:"Google Scholar/arXiv/IEEE/ACM/知网。",estimatedHours:10,diff:"medium"},
  {id:"in-course-07",order:7,slug:"PaperReading",title:"论文阅读、摘要提取与结构化笔记",description:"论文结构、摘要提取、阅读笔记。",estimatedHours:10,diff:"hard"},
  {id:"in-course-08",order:8,slug:"TechDocs",title:"技术文档、官方资料与源码阅读",description:"官方文档、技术规范、源码分析。",estimatedHours:8,diff:"hard"},
  {id:"in-course-09",order:9,slug:"DataReports",title:"数据资料、报告与行业信息检索",description:"行业报告、数据平台、统计资料。",estimatedHours:8,diff:"hard"},
  {id:"in-course-10",order:10,slug:"KnowledgeBase",title:"资料整理、标签、目录与知识库建设",description:"标签体系、目录结构、知识库工具。",estimatedHours:10,diff:"hard"},
  {id:"in-course-11",order:11,slug:"ResearchQuestion",title:"研究问题拆解与信息地图",description:"研究问题框架、信息搜索地图。",estimatedHours:8,diff:"hard"},
  {id:"in-course-12",order:12,slug:"Citation",title:"引用规范、版权意识与学术诚信",description:"引用格式、版权知识、学术不端。",estimatedHours:8,diff:"hard"},
  {id:"in-course-13",order:13,slug:"ResearchReport",title:"研究报告、调研报告与资料综述",description:"报告结构、综述方法、资料整合。",estimatedHours:10,diff:"hard"},
  {id:"in-course-14",order:14,slug:"ILProject",title:"信息检索综合项目与研究作品集",description:"综合研究项目、资料作品集。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["掌握检索技巧","能评估信息质量","会做研究报告","有信息素养"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"in-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["InfoLit"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"IL课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["信息素养","信息能力"],["信息检索","搜索技巧"],["关键词","搜索词"],["布尔运算","逻辑检索"],["高级搜索","精确检索"],["可信度","信息质量"],["事实核查","验证"],["学术搜索","文献检索"],["论文阅读","学术阅读"],["引用规范","引用格式"],["版权","知识产权"],["知识库","信息管理"],["研究问题","研究方向"],["调研报告","研究报告"],["信息源","信息来源"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"in-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"InfoLit",tags:["InfoLit"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"in-kp-"+String(k.length+1).padStart(4,"0"),name:"IL概念"+(k.length+1),description:"IL概念",category:"InfoLit",tags:["InfoLit"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["IL入门","SearchEngine","AdvancedSearch","SourceEval","FactCheck","AcademicSearch","PaperReading","TechDocs","DataReports","KnowledgeBase","ResearchQuestion","Citation","ResearchReport","ILProject"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"信息素养核心？",["发现评价和有效利用信息","会打字","会上网","会用搜索引擎"],"A","easy"],[1,"布尔运算AND作用？",["缩小范围","扩大范围","排除","排序"],"A","easy"],[2,"site:用法？",["限定搜索特定网站","搜索站点地图","搜索网页标题","搜索文件类型"],"A","easy"],[3,"可信度判断依据？",["来源/作者/时效性","页面美观","网站名称","信息长短"],"A","medium"],[4,"事实核查方法？",["交叉验证多源","只看标题","只看评论","只看摘要"],"A","medium"],[5,"Google Scholar用途？",["学术文献搜索","社交网络","购物搜索","地图搜索"],"A","medium"],[6,"论文摘要包含？",["研究目的/方法/结果","全文内容","作者简介","参考文献"],"A","hard"],[7,"官方技术文档特点？",["权威和准确","容易理解","简短","有趣"],"A","medium"],[9,"研究问题拆解第一步？",["定义核心问题","搜集资料","读论文","写报告"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"in-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:700},{type:"multiple_choice",min:300},{type:"true_false",min:300},{type:"fill_blank",min:300},{type:"short_answer",min:800},{type:"case_analysis",min:1400}];
  while(qid<=3500){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="in-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s=["关于信息检索"+ch+"以下正确的是？",""+ch+"的核心是？","以下哪个不是"+ch+"的内容？"][~~(Math.random()*3)];o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"}});a="A";}
    else if(it.type==="multiple_choice"){s="信息检索"+ch+"哪些正确？（多选）";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"}});a="AB";}
    else if(it.type==="true_false"){s=ch+"是信息检索的重要概念。（判断）";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="信息检索"+ch+"中____是关键。";o=[{label:"A",text:"____"}];a="关键";}
    else if(it.type==="short_answer"){s="简述"+ch+"在信息检索中的作用。";o=[{label:"A",text:"简答"}];a=ch+"能提高检索效率。";}
    else if(it.type==="case_analysis"){s="信息检索"+ch+"案例：设计方案。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"in-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["搜索课程资料","查找官方文档","检索论文","比较技术方案","调研数据库选型","调研前端框架","调研云服务","核查新闻","判断可信度","论文摘要笔记","技术报告整理","行业报告分析","资料卡片整理","Zotero文献库","研究报告写作","引用规范","版权风险识别"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"in-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握信息素养",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"问题",description:"分析"},{order:2,title:"方案",description:"设计"},{order:3,title:"执行",description:"实施"},{order:4,title:"验证",description:"检查"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"IL路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"in-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["信息素养","信息检索","布尔运算","可信度","事实核查","学术搜索","论文阅读","引用规范","知识库","版权","关键词","高级搜索","文献管理","研究报告","信息源"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["IL概念"+i,"IL概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"in-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"InfoLit",tags:["InfoLit"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["信息问题"+(i+1)+"?","信息问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"in-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"InfoLit",tags:["InfoLit"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["InfoLit"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["InfoLit"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["InfoLit"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["InfoLit"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["InfoLit"]});});return e;}
async function main(){
  console.log("Gen InfoLit...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-information-literacy",slug:"module-information-literacy",title:"信息检索资料整理与研究能力",subtitle:"面向大学生和研究型学习者",description:"面向大学生技术学习者和研究型学习者的搜索技巧关键词设计资料筛选事实核查论文阅读信息源评价引用规范资料整理研究问题拆解与调研报告训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["信息检索","信息素养","资料整理","事实核查","论文阅读","研究能力","引用规范","调研报告"],estimatedHours:130,difficulty:"beginner",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F50D}",repoUrl:"https://github.com/openskill-galaxy/module-information-literacy",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
